// <auto-generated />
using System;
using Kalkulator.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kalkulator.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517180809_DodajWiekPracownika")]
    partial class DodajWiekPracownika
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kalkulator.API.Models.Absencja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LiczbaDni")
                        .HasColumnType("integer");

                    b.Property<int>("PensjaId")
                        .HasColumnType("integer");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("WspolczynnikZasilku")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PensjaId");

                    b.ToTable("Absencje");
                });

            modelBuilder.Entity("Kalkulator.API.Models.ParametryFirmy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Rok")
                        .HasColumnType("integer");

                    b.Property<decimal>("StawkaWypadkowa")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ParametryFirmy");
                });

            modelBuilder.Entity("Kalkulator.API.Models.ParametryGlobalne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FgspProcent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FunduszPracyProcent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KwotaWolnaOdPodatku")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LimitPitZero")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProgPodatkowyPit")
                        .HasColumnType("numeric");

                    b.Property<int>("Rok")
                        .HasColumnType("integer");

                    b.Property<decimal>("SkladkaChorobowaProcent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SkladkaEmerytalnaProcent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SkladkaRentowaFirmProcent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SkladkaRentowaPracProcent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SkladkaZdrowotnaProcent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StawkaPit1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StawkaPit2")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ParametryGlobalne");
                });

            modelBuilder.Entity("Kalkulator.API.Models.PensjaMiesieczna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Miesiac")
                        .HasColumnType("integer");

                    b.Property<decimal>("Nadgodziny")
                        .HasColumnType("numeric");

                    b.Property<int>("PracownikId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Premia")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Prowizja")
                        .HasColumnType("numeric");

                    b.Property<int>("Rok")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SwiadczenieZfss")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WynagrodzenieZasadnicze")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PracownikId", "Rok", "Miesiac")
                        .HasDatabaseName("IX_PensjeMiesieczne_Pracownik_Rok_Miesiac");

                    b.ToTable("PensjeMiesieczne");
                });

            modelBuilder.Entity("Kalkulator.API.Models.Pracownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("KapitalPoczatkowyZus")
                        .HasColumnType("numeric");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("Plec")
                        .HasColumnType("character(1)");

                    b.Property<int>("StazPracyLata")
                        .HasColumnType("integer");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("integer");

                    b.Property<int>("WiekObecny")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId")
                        .IsUnique();

                    b.ToTable("Pracownicy");
                });

            modelBuilder.Entity("Kalkulator.API.Models.ProfilPodatkowy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("KupStandardKwota")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Pit2Kwota")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PpkStawkaPracodawcy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PpkStawkaPracownika")
                        .HasColumnType("numeric");

                    b.Property<int>("PracownikId")
                        .HasColumnType("integer");

                    b.Property<string>("StatusPitZero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("WspolczynnikAutorskiKup")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PracownikId")
                        .IsUnique();

                    b.ToTable("ProfilePodatkowe");
                });

            modelBuilder.Entity("Kalkulator.API.Models.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyAktywny")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataOstatniegoLogowania")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("Kalkulator.API.Models.WynikKalkulacji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BazaBruttoPrzepracowana")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DataWyliczenia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FunduszGwarSwiadczen")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FunduszPracy")
                        .HasColumnType("numeric");

                    b.Property<int>("PensjaId")
                        .HasColumnType("integer");

                    b.Property<int>("PodstawaOpodatkowaniaPit")
                        .HasColumnType("integer");

                    b.Property<decimal>("PpkPracodawca")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PpkPracownik")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SkladkaChorobowaPracownik")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SkladkaEmerytalnaPracodawca")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SkladkaEmerytalnaPracownik")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SkladkaRentowaPracodawca")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SkladkaRentowaPracownik")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SkladkaWypadkowaPracodawca")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SkladkaZdrowotna")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SuperBrutto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WynagrodzenieChoroboweFirma")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WynagrodzenieNetto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ZaliczkaPit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ZasilkiZus")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PensjaId")
                        .IsUnique();

                    b.ToTable("WynikiKalkulacji");
                });

            modelBuilder.Entity("Kalkulator.API.Models.Absencja", b =>
                {
                    b.HasOne("Kalkulator.API.Models.PensjaMiesieczna", "PensjaMiesieczna")
                        .WithMany("Absencje")
                        .HasForeignKey("PensjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PensjaMiesieczna");
                });

            modelBuilder.Entity("Kalkulator.API.Models.PensjaMiesieczna", b =>
                {
                    b.HasOne("Kalkulator.API.Models.Pracownik", "Pracownik")
                        .WithMany("PensjeMiesieczne")
                        .HasForeignKey("PracownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pracownik");
                });

            modelBuilder.Entity("Kalkulator.API.Models.Pracownik", b =>
                {
                    b.HasOne("Kalkulator.API.Models.Uzytkownik", "Uzytkownik")
                        .WithOne()
                        .HasForeignKey("Kalkulator.API.Models.Pracownik", "UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("Kalkulator.API.Models.ProfilPodatkowy", b =>
                {
                    b.HasOne("Kalkulator.API.Models.Pracownik", "Pracownik")
                        .WithOne()
                        .HasForeignKey("Kalkulator.API.Models.ProfilPodatkowy", "PracownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pracownik");
                });

            modelBuilder.Entity("Kalkulator.API.Models.WynikKalkulacji", b =>
                {
                    b.HasOne("Kalkulator.API.Models.PensjaMiesieczna", "PensjaMiesieczna")
                        .WithOne("WynikKalkulacji")
                        .HasForeignKey("Kalkulator.API.Models.WynikKalkulacji", "PensjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PensjaMiesieczna");
                });

            modelBuilder.Entity("Kalkulator.API.Models.PensjaMiesieczna", b =>
                {
                    b.Navigation("Absencje");

                    b.Navigation("WynikKalkulacji");
                });

            modelBuilder.Entity("Kalkulator.API.Models.Pracownik", b =>
                {
                    b.Navigation("PensjeMiesieczne");
                });
#pragma warning restore 612, 618
        }
    }
}
